language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE="xapi-stdext"
    - PINS="stdext:. xapi-stdext:. xapi-stdext-bigbuffer:. xapi-stdext-date:. xapi-stdext-deprecated:. xapi-stdext-encodings:. xapi-stdext-monadic:. xapi-stdext-pervasives:. xapi-stdext-range:. xapi-stdext-std:. xapi-stdext-threads:. xapi-stdext-unix:. xapi-stdext-zerocheck:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
  matrix:
    - DISTRO="debian-9-ocaml-4.07"
