language: c
os: linux
dist: xenial
services: docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - source xs-opam-ci.env
script: bash -ex .travis-docker.sh
env:
  global:
    - PINS="stdext:. xapi-stdext-date:. xapi-stdext-encodings:. xapi-stdext-pervasives:. xapi-stdext-std:. xapi-stdext-threads:. xapi-stdext-unix:. xapi-stdext-zerocheck:."
  jobs:
    - PACKAGE="stdext"
    - PACKAGE="xapi-stdext-encodings"
    - PACKAGE="xapi-stdext-date"
    - PACKAGE="xapi-stdext-std"
